### ISSUE TITLE
Get OpenGraph to work

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#117]
## Study the SEO plugin
Make it do what it should!

Have a look at praqma's web or [lakruzz.com](https://github.com/lakruzz/lakruzz.com)

**Comment by carolineolivia** [comment]
I am reading and working with this [article](https://blog.webjeda.com/optimize-jekyll-seo/). It is really good :) Yay, i am learning!

### But!! It came with a really nice idea! That we could make a share function for our gigs and maybe our stories? Share to linkedin maybe? @lakruzz @bentreadwell

**Comment by carolineolivia** [comment]
I have also added a few new plugins on the site. Ex: sitemap plugin. It automatically create a sitemap for us, so the bots on the search engines can crawl our site and index it :) It will also rank it better.

**Comment by lakruzz** [comment]
YES! Good Thinking!

**Comment by carolineolivia** [comment]
I have made a lot of meta tags, actually both for facebook and twitter, so when i have implemented the touch icon i will commit and check the workings of all the stuff i made. If it looks like sh*t i will work on with it.
