### ISSUE TITLE
(optional) fix - HTTPS connection refused

### ISSUE THREAD

**Issue by Ansty93** [prolike/prolike.io#140]
## Issue
The website www.prolike.io refuses connections made with HTTP**S** protocol

## How to reproduce the error
Goto [https://prolike.io](https://www.prolike.io )

## The solution
Maybe a worth read:
https://help.github.com/en/articles/securing-your-github-pages-site-with-https

**Comment by bentreadwell** [comment]
Issue seems to have been resolved. Cannot reproduce error.
