### ISSUE TITLE
Update - Force browser to reload cache file

### ISSUE THREAD

**Issue by Ansty93** [prolike/prolike.io#141]
## Issue
The browser trend to reuse the old cached js/css files. You can to force the browser to reload the files.

## Readable materials
https://www.c-sharpcorner.com/article/how-to-force-the-browser-to-reload-cached-js-css-files-to-reflect-latest-chan/
https://www.impressivewebs.com/force-browser-newest-stylesheet/

**Comment by bentreadwell** [comment]
Seems fixed.
