### ISSUE TITLE
Install ghi on windows

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#15]
The [GHI](https://github.com/stephencelis/ghi) CLI is a ruby project - ruby runs native on *nix and MacOs  - but it's  a hazzle to install on Windows. We have two options:

- [ ] Clone and `/stephencelis/ghi` and fix with a DOCKERFILE
- [ ] Make a smooth ruby install on windows and `gem install ghi`
- [ ] Add it to the [`lakruzz/jekyll-plus`](https://github.com/lakruzz/jekyll-plus) (It's already based on ruby)

**Comment by bentreadwell** [comment]
A guide for installing ghi on Windows already exists within a @Praqma repository.

https://github.com/Praqma/git-phlow/blob/master/docs/installation.md
