### ISSUE TITLE
Create initial wireframe

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#17]
The website is on the verge of having a face lift. But, before starting to develop the new website, a high-fidelity prototype is needed, in order to accomidate @lakruzz's needs, while at the same time, serve as a guideline for the development phase.

Adobe XD is going to be the tool for the prototype, which will be made responsive for web, tablet and desktop. Concepts from design thinking will be used for the creation of the prototype.

This issue is a spin off from #16

**Comment by bentreadwell** [comment]
To-do-list

- [ ] Create wireframe for web, tablet and mobile - clear every detail with Jonathan.

- [ ] A B test wireframe with Lars - implement thoughts and ideas.

- [ ] Write case study for wireframe - make sure to talk about design process with Jonathan and describe test results from Lars.

- [ ] Create loop header video for actual website.
