### ISSUE TITLE
Projects Prolike mockup

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#222]
We've started to make a mockup for what'll become our Projects Prolike Project 🤓 

https://xd.adobe.com/view/d064a353-85fb-4e60-56d1-88c39eea2f7a-a655/?fullscreen&hints=off

**Comment by bentreadwell** [comment]
Updated version: https://xd.adobe.com/view/d064a353-85fb-4e60-56d1-88c39eea2f7a-a655/?hints=off

**Comment by sygdrome** [comment]
@bentreadwell You got more of them updates?

**Comment by bentreadwell** [comment]
It's been implemented so nicely! 😂 

http://stage.prolike.io/
