### ISSUE TITLE
Creating door sign

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#233]
For a long time now, we've talked about making a new sign for our door at our offices in Allerød. This is a very creative assignment, and pathes the way for having a go at a few different itterations of what would make an awesome final sign,

**Comment by bentreadwell** [comment]
## 1. Simple Existing Logo

![image](https://user-images.githubusercontent.com/32065613/66638188-c29bc400-ec14-11e9-9baa-04db65d16529.png)

**Comment by bentreadwell** [comment]
## 2. Colorfull Logo

![image](https://user-images.githubusercontent.com/32065613/66638381-1dcdb680-ec15-11e9-9f7f-3701cec2d544.png)

**Comment by bentreadwell** [comment]
## 3. Monochrome

![image](https://user-images.githubusercontent.com/32065613/66640355-1ad4c500-ec19-11e9-990c-a1f3440ad132.png)

**Comment by bentreadwell** [comment]
Hej @lakruzz, kan du give mig noget feedback omkring de her tre versioner? Er der noget du kan lide, er der noget du ikke kan lide? Jeg tænker at de her tre er forskellige nok til, at vi kan vælge en retning af gå ned af i forhold til æstetik før om jeg beslutter mig for at poste en masse timer i noget som vi ikke kan lide alligevel 😅

**Comment by carolineolivia** [comment]
@bentreadwell @lakruzz 
Tænkte om vi "også" skulle have et til rePublicDomain? Måske opdelt?

**Comment by bentreadwell** [comment]
We've ordered one, finally!
