### ISSUE TITLE
Style infographics page

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#235]
Back in #234 we made the bare minimum to get our page map for our infographics page to work. The styling we purposefully left out for another time, which is this issue.

**Comment by bentreadwell** [comment]
Get crackin

**Comment by sygdrome** [comment]
Første udkast, thoughts?
![Artboard 1](https://user-images.githubusercontent.com/26737628/67680897-87c3bb00-f98c-11e9-95ae-0fb75a0c4df3.png)
