### ISSUE TITLE
Create another infographics

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#237]
We made another infographic that we would like to digitalize at some point for further use.

![image](https://user-images.githubusercontent.com/32065613/66654049-a3635d80-ec39-11e9-8b27-fb87bcb9be6f.png)

**Comment by sygdrome** [comment]
Første udkast, thoughts?
![Artboard 1](https://user-images.githubusercontent.com/26737628/67681523-ca39c780-f98d-11e9-9eac-15291d1bd40e.png)

**Comment by carolineolivia** [comment]
@bentreadwell 
@sygdrome 
Tænker at teksten i Agreement kunne være hvid?
Er lidt usikker med den orange baggrund, den minder lidt om Praqma. Hehe. Kan den være en anden farve?

**Comment by carolineolivia** [comment]
Ellers er det skide godt 👍

**Comment by sygdrome** [comment]
@bentreadwell @carolineolivia har lavet et par variations, thoughts?
1
![flowMVPV2](https://user-images.githubusercontent.com/26737628/67750890-64524c00-fa30-11e9-889f-2a19d1d45566.png)
2
![FlowMVPV3](https://user-images.githubusercontent.com/26737628/67750896-674d3c80-fa30-11e9-85c2-50b874d0ee82.png)
3
![flowMVPV4](https://user-images.githubusercontent.com/26737628/67750903-687e6980-fa30-11e9-8ae3-102b3ce4196c.png)

**Comment by carolineolivia** [comment]
@bentreadwell @sygdrome 
Jeg kan godt lide den sidste :)

**Comment by carolineolivia** [comment]
@bentreadwell @sygdrome 
Så.. Hvor skal denne bruges, nu hvor der kun skal være stories (de nye) format på vores produkter og infographic?
