### ISSUE TITLE
New website layout implementation

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#25]
Alright, so this issue serves as our end goal for our mock up process; the first draft of the full website should resemble our [mockup](https://xd.adobe.com/view/351811e1-5fdd-4608-679f-ead1c7d8fe4d-4329/?fullscreen&hints=off). This of course doesn't imply, that this is our final design for our website, but it should allow us to have a decent starting point for our next grooming session.

This issue is also the parent issue for #26. The distinction to be made is, that this issue - as mentioned above - is our end goal for the mock up; it's done when our entire website looks like our mock up. Issue #26 is for the implementation the first page of our website - to get the ball rolling for us.

To infinity and beyond!

**Comment by lakruzz** [comment]
Closed with [2.0.0.](https://github.com/prolike/prolike.io/releases/tag/2.0.0)
