### ISSUE TITLE
Implement consistent page title layout

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#257]
Right now, we haven't settled upon a consistent use for our page titles across our website. This issue will implement a consitent format for now, which we can always change later on.

The format should be as follows:

Website

Page - Website

Sub page - Page - Website

**Comment by carolineolivia** [comment]
@bentreadwell @sygdrome 
Aaah, now i understand. Me and Anders discussed what you meant by this hahah.

So it is like in title? Like this?
![image](https://user-images.githubusercontent.com/17065639/67701584-7b515980-f9b0-11e9-9ff5-7927aea8b753.png)

**Comment by bentreadwell** [comment]
Exactly, for example, have a look at how YouTube and Google have theirs 👌
