### ISSUE TITLE
Create layout for projects.prolike

### ISSUE THREAD

**Issue by sygdrome** [prolike/prolike.io#259]
@carolineolivia has created the functionality for a customer to see the status of their product.
So now we need to implement the layout that @bentreadwell has made.

https://xd.adobe.com/view/d064a353-85fb-4e60-56d1-88c39eea2f7a-a655/?hints=off

**Comment by carolineolivia** [comment]
@sygdrome @bentreadwell 
Husk at der ikke må ligge u-estimerede eller u-prioterede issues i To Do <3 :)

**Comment by sygdrome** [comment]
@carolineolivia 
Mener du den milestone du har tilføjet? Dette issue havde allerede en prio 1 og kan ikke see nogen valgmulighed til time estimate.

**Comment by carolineolivia** [comment]
@sygdrome 
For at give et estimat, skal man være på issuet i zenhub boardet, da det er en funktion zenhub har. Alle issues i ToDo pipelinen på zenhub boardet skal have en priotet og et estimat. Ellers får vi bøvl med Lars ;)

**Comment by sygdrome** [comment]
@carolineolivia 
Når det forklarer det! Jeg havde ikke Zenhub på min egen pc. I morgen kunne det være fedt hvis vi kunne sætte os ned og finde out af hvordan vi tackler alle disse issues. :)
