### ISSUE TITLE
Design mockup for gigs page - and the individual gig pages

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#34]
We should in collaboration @bentreadwell design the mockups for both the **gigs page** (Where all the gigs are shown in columns) - and also make a mockup for the **individual gig page** (where all text and info is shown)

Examples we can get inspired by: [dunked](https://dunked.com/examples)

I don't think pics are necessary in the gigs page, but let's discuss it. It could be delicious to have a picture with a faded box in the center containing the text/info.

related to #18

**Comment by bentreadwell** [comment]
After having spent some time prototyping the **Gigs** page in Adobe XD, our [conceptual mockup](https://xd.adobe.com/view/12f7b48f-57d2-423d-4f8b-0c4c0e19099d-64c6/?fullscreen&hints=off) has arrived. Having gotten the go ahead from @lakruzz, @carolineolivia is now able to implement the layout on the website.

If - further down the line - the team wants to revisit the design of the mockup, the opportunity is there!
