### ISSUE TITLE
Design mockup for menu

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#39]
We have to make a mockup for the menu/navi.

@bentreadwell Is it something to talk about or do you know exactly how it should be?

**Comment by bentreadwell** [comment]
Quick and dirty [mockup](https://xd.adobe.com/view/74bd58f9-e5a3-4697-63a0-e8f784cff794-028c/?fullscreen&hints=off) for our menu. 

Nothing final, but atleast we've got something to go by for now.
