### ISSUE TITLE
TimeReg form

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#414]

**Comment by carolineolivia** [comment]
@lakruzz 
Hvad skal dette issue?

**Comment by carolineolivia** [comment]
Alrady been made

**Comment by lakruzz** [comment]
NO! - it's not online anywhere.

@carolineolivia if this is a duplicate issue, then please make a reference

**Comment by carolineolivia** [comment]
@lakruzz 
Er det her relevant mere?
