### ISSUE TITLE
Implement micro interactions

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#43]
During an initial brainstorm for the development process of the website, we circled around the idea of implementing small micro interactions. This would help the enhance the overall **user experience** of the site, and also help to make the site come more alive.

This issue relates to #42, in that both are heavily focused on the **user experience**, and the **user interface**. For now, we're short on examples, but as we work with the site daily, we'll eventually be able to pinpoint ideal locations for these micro interactions.

If you want to read more about how micro interactions helps to make the site more alive, you can check out this article: https://uxdesign.cc/micro-interactions-why-when-and-how-to-use-them-to-boost-the-ux-17094b3baaa0.

**Comment by lakruzz** [comment]
Let's revisit this when it pops up in context
