### ISSUE TITLE
Menu toggle animation

### ISSUE THREAD

**Issue by bentreadwell** [prolike/prolike.io#47]
Having decided to have a hamburger menu on the desktop version of our website, we stumbled upon something we knew we would love to implement; an eye-catching animation whenever the user toggled the site's menu, wether that be desktop or mobile.

An example that convinced us of having such a menu animation would be [this one](https://www.benjimessmer.com/). Remember to view it in the mobile version, and rejoice with the awesomeness of the animation! This would eventually be something we would absolutely love to have!

**Comment by carolineolivia** [comment]
I guess its done :)
