### ISSUE TITLE
Get statuses

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#477]
Restructure the GET of statuses.
I will probably use some of the old code, but in the light of having a new api i can't predict if it is going to be quick. This will also be needed to get from github api, therefore one more request :(

@lakruzz Prio?

**Comment by lakruzz** [comment]
Hmmm - what does "get statuses" mean? What statuses? @carolineolivia

**Comment by carolineolivia** [comment]
@lakruzz Getting the statuses we write for our costumers and label as status.
![image](https://user-images.githubusercontent.com/17065639/72841239-43e40780-3c96-11ea-8a7a-8cc1ab043034.png)
