### ISSUE TITLE
Get pipelines

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#478]
Again, I can probably use some old code, plus all this data we have directly in our own API - or it will be easy to get from Zenhub.

@lakruzz Prio?

**Comment by lakruzz** [comment]
What does it mean @carolineolivia is it a tile with link to the build pipeline on Circle CI ...or?

**Comment by carolineolivia** [comment]
It's a tile where you can see all the zenhub columns/pipelines
![image](https://user-images.githubusercontent.com/17065639/72841116-ff586c00-3c95-11ea-9b14-5fb03b415755.png)
