### ISSUE TITLE
Find templates that we wanna support

### ISSUE THREAD

**Issue by sygdrome** [prolike/prolike.io#481]
@carolineolivia and I need to find some amount of templates that we can easily support. Customers can still ask about specific templates if wanted to.

**Comment by carolineolivia** [comment]
@sygdrome 
I've got these 👍 

https://jekyllthemes.io/theme/forty-jekyll-theme

https://jekyllthemes.io/theme/airspace-jekyll

https://jekyllthemes.io/theme/ubuild-jekyll-theme

http://themes.jekyllrc.org/grayscale/

http://themes.jekyllrc.org/mediator/

**Comment by sygdrome** [comment]
https://jekyllthemes.io/theme/agency-jekyll-theme

https://jekyllthemes.io/theme/landing-page-theme

https://jekyllthemes.io/theme/minimal-mistakes

**Comment by carolineolivia** [comment]
done
