### ISSUE TITLE
Event isn't live

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#521]
The event appears to be live:

![image](https://user-images.githubusercontent.com/155492/74682750-42d7c480-51c7-11ea-8221-fefec184ffd1.png)

But the page isn't!

![image](https://user-images.githubusercontent.com/155492/74682717-2471c900-51c7-11ea-98a2-4f76d0647695.png)

It works on my local docker

**Comment by carolineolivia** [comment]
@lakruzz 
Works fine to me
![image](https://user-images.githubusercontent.com/17065639/74684067-250c5e80-51cb-11ea-8a86-3bc003b93461.png)

**Comment by lakruzz** [comment]
@carolineolivia it's live now, I can also see that it was compiled and delivered to the repo correctly - what happened? Do you know?
