### ISSUE TITLE
Get the Alvarotrigo license in order

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#543]
![image](https://user-images.githubusercontent.com/17065639/75531165-43b4f580-5a14-11ea-88da-cfd938b47e99.png)

**Comment by lakruzz** [comment]
https://alvarotrigo.com/fullPage/pricing/

**Comment by carolineolivia** [comment]
@lakruzz 
Because Prolike.io is open source we can request a free license. I have no idea how long it will take them to reply the request, but it wont take long to request it.

**Comment by carolineolivia** [comment]
Hurray!!!
![image](https://user-images.githubusercontent.com/17065639/78123319-45584b80-740e-11ea-9b92-6ff10d24ff5f.png)
