### ISSUE TITLE
In the large media query - expand the menu in the top bar

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#592]
![image](https://user-images.githubusercontent.com/155492/76060433-95fc9600-5f81-11ea-938b-65a8d2cc4da3.png)

I like how you trimmed the menu to fewer entries - I think it would make sense to add the feature to the the largerest media query, that we don't use the burger menu there, but instead expand them entries on the top bar. 

I'd like your feed back on this - what do you think?

**Comment by sygdrome** [comment]
@lakruzz Fully agree on making a more traditional navigation bar on desktop views.
@andreasgolles has gotten some [feedback](https://docs.google.com/document/d/1oWigQDclJKCE2x-roFnhkb1nN95eGdlLwxA32rTXuPo/edit?ts=5e5d07b0) on our site where some others also commented on the menu as well as the anything section like you have mentioned in #591
