### ISSUE TITLE
What's with all the horizontal rulers?

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#593]
![image](https://user-images.githubusercontent.com/155492/76061166-3a330c80-5f83-11ea-8074-7baa9d5fd8b9.png)

There are _a lot_ of horizontal rules on our stories lay-out - what the logic, they seem to come in quite arbitrary order.

Think we should go for a more minimalistic design. (no `<hr>`s)

...any thoughts? feed-back?

**Comment by sygdrome** [comment]
@lakruzz I agree. They seem to come from the markdown itself and started to be added back in #346 and #350 Should I go through and remove them from the posts?
