### ISSUE TITLE
Figure out who our partners are and create a list of them

### ISSUE THREAD

**Issue by sygdrome** [prolike/prolike.io#622]
While we have Phable and Reepay as partners we might have more, maybe. Research this so we can get all of them on our site.

**Comment by lakruzz** [comment]
NIKE:

* Phable
* Reepay
* CPH Business (are we allowed to announce them as partners?)
* KEA (are we allowed to announce them as partners?)
* Tenzion (_are_ we partners ...really?)
* Gastronomisk Innovation/Atelier 1B
