### ISSUE TITLE
Create Moodle content for service

### ISSUE THREAD

**Issue by sygdrome** [prolike/prolike.io#626]
With the times we are in it has become relevant to create Moodle as a service and push it to SoMe

Some existing text exists here.
https://docs.google.com/document/d/1fb-0wv3qcn_H0vekt2dB6TzymeBRqi85Hhyhy6Kerv8/edit

**Comment by lakruzz** [comment]
Note: 
Use  the shared drives en Google for google docs.

**Comment by lakruzz** [comment]
https://docs.google.com/document/d/1YSt9V-KS2CN4chJuoc2OjZ27guiFQjJzB7mXjTFT5mU/edit

**Comment by lakruzz** [comment]
Make this part of a campaign (Epic)

EPIC: Sell moodle as a product

- [ ] What are we selling? (create the quote you want to offer)
- [ ] Identify potential customers
- [ ] How do we reach them?
- [ ] Call to action! What are we hoping the co, when they hear our quote
- [ ] Create Moodle as a Service landing page (this issue)
- [ ] SoMe the Landing page
...etc

**Comment by lakruzz** [comment]
This is content, so the product is a reviewed google doc

**Comment by sygdrome** [comment]
New docs https://docs.google.com/document/d/1X6-_2BTusHlasvlTLJvFNGjpgcbRAgJRWq0kfqtyFeA/edit#

**Comment by sygdrome** [comment]
This has been completed and the finished doc will be posted in the epic
