### ISSUE TITLE
GIG campaign

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#627]
### What are we selling? 
Our products. A [quote template](https://docs.google.com/document/d/1s5nUXkfv1Cz0RSTyIk2MDwQxns-WGh_kpyyJeL3Mw8k/edit#heading=h.ke60i8xf30oj) will be made for this campaign that the people who reach out to us will get.

### Identify potential customers
Our potential customers will be people interested in getting some kind of service, based on what they learn when they read the stories.

### How do we reach them?
We will reach the potential customers by writing som Gig landing pages and share the Gig page (The overview page) on social media, with a custom caption and selected hashtags. 

### Call to action! 
What we hope the customer will do, is contacting us, by phone or via our call to action, which we will develop through this campaign.

### Create the Gigs landing page and the Gig pages.
Every customer we can write a story about is getting a page. A landing page will show all of our gigs.

**Comment by carolineolivia** [comment]
@lakruzz 
Do we need permission from our customers to write these stories?

**Comment by lakruzz** [comment]
Make it whole!

As in #626 

Whats that plan? Why do we do it? what are we hoping to achieve? think "Landing page" and SoMe ...and alla that jazz!

**Comment by lakruzz** [comment]
Quote template: https://docs.google.com/document/d/1-kX5RCPnM2ctLaPDpJlVYgXK_Z1Eb5pQYPP4bkE8lfY

**Comment by lakruzz** [comment]
Maybe develop a format for what a gig story is?

**Comment by lakruzz** [comment]
More Issues?
* SoMe campaign?
* Update the gig layout?
* Improve the call-to-action?
