### ISSUE TITLE
Create a new infographic

### ISSUE THREAD

**Issue by HeinLarsen** [prolike/prolike.io#628]
After our meeting with Tenna and Renee, it has become clear that they need some assistance in selling our sites. We will do this by creating an infographic on our website that tells more about our technology stack and why possible costumers shouldn't be afraid to be stuck with us.

**Comment by lakruzz** [comment]
make this part of a holistic epic - see comment in #626

**Comment by lakruzz** [comment]
@sygdrome  is looks like this one is in the wrong epic?

**Comment by sygdrome** [comment]
@lakruzz I thought that was the meaning based on your previous comment. Should I create a new epic just for this or leave it without an epic?
