### ISSUE TITLE
Fix double scrolling on our page

### ISSUE THREAD

**Issue by HeinLarsen** [prolike/prolike.io#630]
We have discovered that on some machines, pages that use fullpage.js double scrolls. This has to be fixed before new infographics can be done.
This might be done by changing the code or finding a new library to use.

**Comment by lakruzz** [comment]
I See the problem on Mac/Chrome - don't know if it's just me?

I see it both on infographics and the front page

**Comment by sygdrome** [comment]
@lakruzz This is ready for you to test on stage. Some people mention changing the scrolling speed to a higher value. You can change this in the initialize.js file.
