### ISSUE TITLE
Review formatting of the gigs

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#639]
When writing the gig, a format will be developed. It will be reviewed shortly over time and changed however we want it to.

To dumb it down this is an issue for:
- Certain people take a look at the Google Doc, and quick decide what to change in the format. This will be done after the first gig is written, and over time when writing the other gigs.
This issue does not end with a commit.

**Comment by carolineolivia** [comment]
@sygdrome 
Da jeg var ude og undersøge CTA's så jeg også flere former for formatering a cases (gigs) og man kunne lave nogle fede ting:

- Quotes
- Kunde faktaboks
- Liste med kompetencer brugt
- flere?

Men jeg synes at vi som minimum kunne lave en liste med de ting vi har brugt, eksempel:
- Jekyll
- Vue.js
- Firebase

Så kan vi senere udvide og bruge dem som tags :)

Hvad siger du til det?

**Comment by sygdrome** [comment]
@carolineolivia Jeg synes det lyder godt, men jeg kunne også godt tænke mig at vi havde en lille "teaser" på den knap der leder ind til det fulde content af gigs. ligesom stories 
![image](https://user-images.githubusercontent.com/26737628/78536139-a48ed500-77ed-11ea-8955-d2ad5253d5ca.png)

**Comment by carolineolivia** [comment]
@sygdrome 
Yes, det tænker jeg også. Jeg kigger på det :)
