### ISSUE TITLE
Get costumers

### ISSUE THREAD

**Issue by sygdrome** [prolike/prolike.io#645]
Now that we have found out who our costumers are and how to reach them, it is time to get them.
If it's by social media, create posts clever hashtags, graphics and text to reach them.
If by phone, call them and pitch moodle.

**Comment by lakruzz** [comment]
I'm making this one last in the order, as the size of this may depend on how the rest of the  epic turns out - we may have to revisit this one - or at least make the 3-hour estime a "Timebox"
