### ISSUE TITLE
Align visual objects

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#649]
![image.png](https://images.zenhubusercontent.com/5c8dfc25777e5f767e4863d6/bb7d7a5f-2dd7-409f-afe7-1042b8839c3b)

**Comment by carolineolivia** [comment]
@sygdrome 
Den kommer til at ligge under den anden faktaboks. Skal den stadig være fixed?

**Comment by sygdrome** [comment]
@carolineolivia Ja de begge kan være fixed

**Comment by carolineolivia** [comment]
@sygdrome 
Yes, god ide :)
